### ISSUE TITLE
I can not update the installed 2.5 with yum

### ISSUE THREAD

**Issue by Azur4** [IssabelFoundation/issabel#10]
Update elastix-pbx-2.5.0-10.noarch
Running rpm_check_debug
ERROR with rpm_check_debug vs depsolve:
rpmlib(FileDigests) is needed by elastix-pbx-2.5.0-10.noarch
rpmlib(PayloadIsXz) is needed by elastix-pbx-2.5.0-10.noarch
Complete!
(1, [u'Please report this error in http://bugs.centos.org/yum5bug'])

**Comment by asternic** [comment]
elastix-pbx update was accidentally added from Issabel4 builds. Anyways, we have repackeged it so it is compatible with Centos5. Please wait a day for the mirrors to catch up and then try: yum clean all and then yum update elastix-pbx.

**Comment by Azur4** [comment]
Ok. Updates successfully
