### ISSUE TITLE
Error al crear servidor SMTP

### ISSUE THREAD

**Issue by grichieri** [IssabelFoundation/issabel#11]
Al intentar definir un servidor SMTP da el siguiente msg de error
Failed to send hello command: Array ( [error] => HELO command failed [detail] => [smtp_code] => [smtp_code_ex] => )

**Comment by asternic** [comment]
Que tipo de servidor estás creando? Me parece que ya está resuelto el tema con este commit:

https://github.com/IssabelFoundation/email_admin/commit/55a9d3675b3afbea43cec84698262476906ca482

**Comment by grichieri** [comment]
Es un server SMTP de gmail normal
Al hacer save da ese error.

No se de cuando es el comit, pero acabo de hacer un yum update y no
actualiza el módulo


2017-05-30 14:01 GMT+02:00 Nicolas <notifications@github.com>:

**Comment by asternic** [comment]
Hola Gerardo,

No se generan paquetes .rpm nuevos con cada commit, sino que se harán seguramente cada mes. Siendo que ayer se realizaron alrededor de 10 commits, no tiene sentido estar actualizando repositorios con el mismo ritmo. Por lo pronto, puedes probar corregir el código tal como indica el commit (no es para nada complicado, es solo una línea), y ver si resuelve el problema. Si es así, se puede cerrar el issue y te puedes quedar tranquilo que la solución estará incluída en el próximo release del respectivo paquete.

Si quieres te puedo dar una mano con ese parche, el archivo modules/remote_smtp/libs/paloSantoEmailRelay.class.php línea 156, cambias:

if(!$smtp->Hello()){

por

if(!$smtp->Hello(getHostname())){

Saludos,

--
Nicolás Gudiño

**Comment by grichieri** [comment]
Ok lo he cambiado pero ahora el codigo de error es otro

Authenticate not accepted from server: Array ( [error] => Authentication is not allowed at this stage [detail] => [smtp_code] => [smtp_code_ex] => )

**Comment by asternic** [comment]
Google no permite accesos remotos si no se los habilita especialmente. seguramente deberás revisar las preferencias de tu cuenta de gmail, puede que hayan bloqueado el acceso y debas permitirlo.

Saludos,

--
Nicolás Gudiño

**Comment by grichieri** [comment]
Gracias Nicolás por el soporte 👍

**Comment by grichieri** [comment]
El problema persiste. 
La misma configuración de correo gmail con REMOTE SMTP en Elastix 2.5 funciona pero en ISSABEL no
Es un problema con la auntentificación TLS porque he probado con una cuenta en 1and1.com que permite enviar a través del puerto 25 y la configura OK, pero en cuanto pones el puerto 587 te da un error de autentificación.

**Comment by asternic** [comment]
Se de gente que está usando gmail/tls sin problemas. Veré si tengo tiempo de probar o consultar con ellos.

**Comment by grichieri** [comment]
Hola Nicolas

He comprobado en una distribución antigua de Issabel, previa a la ISO el
funcionamiento de Remote SMTP con gmail y fue OK

Luego hice un yum-update y al intentar registrar de nuevo la cuenta de
gmail en Remote SMTP el mismo error que comentaba antes.

Authenticate not accepted from server: Array ( [error] => Authentication is
not allowed at this stage [detail] => [smtp_code] => [smtp_code_ex] => )

Con lo que algo ha cambiado ahí.
Pruebalo cuando puedas y me comentas

Saludos

2017-05-31 12:51 GMT+02:00 Nicolas <notifications@github.com>:

**Comment by asternic** [comment]
Hola Gerardo,

Yo no lo he probado personalmente, sin embargo tengo reportes de gente autenticando sin problemas con gmail/centos7/issabel4.

Hay que investigar un poco  mejor el tema, yo sigo pensando que puede ser un problema de autenticación en google, son bastante estrictos para permitir conexiones desde nuevos clientes.

Saludos,

--
Nicolás Gudiño

**Comment by grichieri** [comment]
Hola Nicolas

La prueba válida es que si en una distribución de Centos7-Issabel 4 antigua
me registro con la cuenta de gmail sin problemas y luego de hacer un
yum-update ya no me deja entonces es que en las actualizaciones se ha
modificado algo que afecta al registro.

Me inclino más a pensar que es algo de php y las versiones

Habrá que echarle un ratito,

Saludos

**Comment by marcoadasilvaa** [comment]
Hola a todos, probé la configuración con un par de cuentas gmail y funciono sin problemas.
En la cuenta gmail cree un password de aplicación por los 2 factores de autenticación. Sin agregar el getHostname presentaba el error que comentas y al agregar el getHostname se registra sin problemas.
![image](https://cloud.githubusercontent.com/assets/4205973/26705229/e2a73018-4702-11e7-981c-642d68884606.png)

**Comment by grichieri** [comment]
Hola Marco

Puedes explicar a que te refieres con getHostname y lo del password de
aplicacion?

Saludos


El 2 jun. 2017 1:46, "Marco A. Da Silva A." <notifications@github.com>
escribió:

Hola a todos, probé la configuración con un par de cuentas gmail y funciono
sin problemas.
En la cuenta gmail cree un password de aplicación por los 2 factores de
autenticación. Sin agregar el getHostname presentaba el error que comentas
y al agregar el getHostname se registra sin problemas.
[image: image]
<https://cloud.githubusercontent.com/assets/4205973/26705229/e2a73018-4702-11e7-981c-642d68884606.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/IssabelFoundation/issabel/issues/11#issuecomment-305650605>,
or mute the thread

**Comment by marcoadasilvaa** [comment]
Con respecto al getHostname, modifique manualmente en mi instalacion de Issabel 4 beta 2 la linea  de código comentada por @asternic  IssabelFoundation/email_admin@55a9d36.

Para la cuenta gmail cree el password de aplicacion en la seccion Mi Cuenta -> Cómo acceder a Google -> Contraseñas de la aplicación -> Generar. El código que te arroje este proceso será el password a emplear en la configuracion del SMTP.

**Comment by grichieri** [comment]
Hola Marco

Lo de cambiar la línea de código en paloSantoEmailRelay.class.php
<https://github.com/IssabelFoundation/email_admin/commit/55a9d36#diff-18cb2e2b1ff834e5bdd2712022e4845e>
ya lo tenía hecho

Lo de generar el password de aplicación que opción seleccionas ?

[image: Imágenes integradas 1]

He intentado en correo y en otra
[image: Imágenes integradas 2]

[image: Imágenes integradas 4]

Y luego la pongo en la configuración de Issabel como password pero ...

[image: Imágenes integradas 5]

El 2 de junio de 2017, 17:09, Marco A. Da Silva A. <notifications@github.com

**Comment by marcoadasilvaa** [comment]
Puedes adjuntar las imágenes directamente desde la pagina de github, vía email no se pueden visualizar.

Las opciones para generar contraseña de aplicacion dentro de gmail es:
Mi Cuenta -> Cómo acceder a Google -> Contraseñas de la aplicación -> Generar

**Comment by grichieri** [comment]
Reenvío el último correo adjuntado las imágenes desde github

Hola Marco

Lo de cambiar la línea de código en paloSantoEmailRelay.class.php ya lo tenía hecho

Lo de generar el password de aplicación que opción seleccionas ?
![imagen](https://cloud.githubusercontent.com/assets/29058920/26783430/6b870eec-49f8-11e7-8cbd-0090740c13fe.png)

He intentado en correo y en otra
![imagen 1](https://cloud.githubusercontent.com/assets/29058920/26783458/8b4b78c6-49f8-11e7-9d90-dcfa01a0dd4b.png)

![imagen 2](https://cloud.githubusercontent.com/assets/29058920/26783463/8ff740bc-49f8-11e7-861f-77bad4f2fe34.png)

Y luego la pongo en la configuración de Issabel como password pero ...

![imagen 3](https://cloud.githubusercontent.com/assets/29058920/26783469/994338a6-49f8-11e7-876f-1568bafb1f21.png)


La ruta desde donde creo estas contraseñas de aplicación es:
https://security.google.com/settings/security/apppasswords

Lo de 
Mi Cuenta -> Cómo acceder a Google -> Contraseñas de la aplicación -> Generar

que comentas te lleva al mismo sitio

**Comment by venturinog** [comment]
Hola, hice la prueba en mi equipo de test y fue satisfactoria.
Podrias chequear que la cuenta de gmail que estas utilizando esta configurada correctamente para poder hacer relay? De ser asi, en algun otro sistema funciona sin inconvenientes?
https://support.google.com/a/answer/176600?hl=es


![captura de pantalla 2017-06-05 a la s 12 32 52](https://cloud.githubusercontent.com/assets/25852954/26790831/91c346d2-49eb-11e7-8c28-8d6133ad1ed9.png)

Saludos.

**Comment by marcoadasilvaa** [comment]
@grichieri me temo que es un problema de la red a la que pertenece ese equipo, quizás un SMTP Relay del CentOS este bloqueando la conexión, tal y como comenta @venturinog

**Comment by venturinog** [comment]
checklist de google para este tipo de configuraciones:
https://support.google.com/mail/answer/7126229

**Comment by asternic** [comment]
Para los que experimentan el problema, por favor prueben con este parche para confirmar si se soluciona:

https://github.com/IssabelFoundation/email_admin/commit/0b810cc18046fa68aae5b3df599bcb246d053e26

Si tienen dudas de como aplicar el cambio, se puede chatear en gitter:

https://gitter.im/IssabelFoundation/Lobby

**Comment by grichieri** [comment]
Solucionado con el parche
IssabelFoundation/email_admin@0b810cc
<https://github.com/IssabelFoundation/email_admin/commit/0b810cc18046fa68aae5b3df599bcb246d053e26>

Y sin necesidad de tener una cuenta con verificación en dos pasos ni con
password de aplicación.

Gracias a todos por los aportes

Saludos
