### ISSUE TITLE
Error Mirror List

### ISSUE THREAD

**Issue by marcoadasilvaa** [IssabelFoundation/issabel#12]
Hello!

The mirror list "http://mirror.issabel.org/?release=4&arch=x86_64&repo=base" return this options:

http://repo.us.issabel.org/issabel/4/base/x86_64/ -> OK
http://repo.es.issabel.org/issabel/4/base/x86_64/ -> Error - Wordpress listing don't configured
http://repo.issabel.org/issabel/4/base/x86_64/ -> OK
http://mirror1.issabel.sipdoc.net/issabel/4/base/x86_64/ -> OK

Please fix.
![image](https://user-images.githubusercontent.com/4205973/27546673-72b71788-5a61-11e7-899e-7fa70abdc9e0.png)

**Comment by bustosjuan** [comment]
The mirror file has been updated to reflect the corrent mirror name.

Just run a yum clean all and then a yum update.

Thanks for letting us know!
