### ISSUE TITLE
Missing Send Fax module 

### ISSUE THREAD

**Issue by wardmundy** [IssabelFoundation/issabel#14]
Not sure if this was an oversight or just something nobody has gotten to yet, but the Send Fax web component appears to be missing from the latest Issabel 4 build...

https://www.packtpub.com/mapt/book/networking_and_servers/9781849519342/6/ch06lvl1sec83/sending-a-fax-from-elastix%2527s-webgui

**Comment by asternic** [comment]
Menu option is inside Fax > Virtual Fax > Send Fax

![image](https://user-images.githubusercontent.com/25182694/27980456-3418059e-6355-11e7-9321-1a634d09b53f.png)

Best regards,

**Comment by wardmundy** [comment]
Thanks. That's what I needed. :-)
