### ISSUE TITLE
Postfix / cyrus imap upper case issue

### ISSUE THREAD

**Issue by whotopia** [IssabelFoundation/issabel#31]
When I attempt to create domain names  in the UI containing upper case characters,  users associated with this domain are not set up correctly on the backend.  

To test, create a domain name, e.g. "BigFoo.Org"  and some user "user@BigFoo.Org"  

Now on the user listing, under Used Space, you will now get "Could not query used disc space"

Trying to log into the webmail will also not work.

If you repeat with the domain name in all lower case it works fine.

**Comment by asternic** [comment]
Ok, latest commit will force lowercase on domain creation. Remember that case is not allowed in domain names, so for the start using uppercase domains is a bad idea. Thanks for the report.
