### ISSUE TITLE
Change sender from Fax doesn't take effect

### ISSUE THREAD

**Issue by cmarodrigues** [IssabelFoundation/issabel#32]
When change sender email address from "Email Template" on Fax sections, doesn't take effect.

The emails are send with uucp@hostname.local

**Comment by cmarodrigues** [comment]
The problem its seems to be from /var/spool/hylafax/bin/issabel-faxevent script.

After make the following change, the problem should be fixed:

`# diff -Naur /var/spool/hylafax/bin/issabel-faxevent.orig /var/spool/hylafax/bin/issabel-faxevent 
--- /var/spool/hylafax/bin/issabel-faxevent.orig	2018-05-30 16:55:43.484268468 +0100
+++ /var/spool/hylafax/bin/issabel-faxevent	2018-05-30 16:53:41.005649448 +0100
@@ -527,6 +527,7 @@
 
     $mail = new PHPMailer();
     $mail->From = $emailInfo['remite'];
+    $mail->setFrom($emailInfo['remite']);
     $mail->FromName = $emailInfo['remitente'];
     $mail->AddAddress($sDestinationEmail);
     $mail->WordWrap = 50;                                 // set word wrap to 50 characters
`

**Comment by asternic** [comment]
Thanks, fixed.
