### ISSUE TITLE
Call recordings 

### ISSUE THREAD

**Issue by marcioelias** [IssabelFoundation/issabel#36]
Hello.

Could anyone help me with call recordings?

All files are recorded correctly, but GUI shows nothing.

**Comment by asternic** [comment]
Hi Marcio, this place is for submitting bugs, informing exactly where the bug lies and ways to reproduce it. It is not for getting support. Please use the forum or telegram groups to get community support, or go to issabel.com for getting commercial/professional support. Thanks!

**Comment by marcioelias** [comment]
Hello. Well for me this is a bug.

I just install Issabel, make all configs to my extensions, trunks, etc. 

Under, PBX / Extensions / {SOME-EXTENSION} / Recording Options, I enabled:

- Inbound External Calls (Always)
- Outbound External Calls (Always)
- Inbound Internal Calls (Always)
- Outbound Internal Calls (Always)
- On Demand Recording (Enable)

And if I navigate at PBX / Call Recordings, it shows me nothing. But looking in the file system the recording files are created correctly.

Supposedly that these files have to appear at GUI not?
