### ISSUE TITLE
api issabel

### ISSUE THREAD

**Issue by Nuxli83** [IssabelFoundation/issabel#37]
I would like to know if there are any api in issabel as in elastix with methods to create phone extensions?

**Comment by asternic** [comment]
Documentation here:

https://github.com/IssabelFoundation/framework/tree/master/framework/html/pbxapi

**Comment by karthik0112** [comment]
Are there any APIs for exposing to create IVR, Announcement, and recordings

**Comment by wagnercorreiadextak** [comment]
Hello, could you tell me how to create users to generate the key for the Issabel API? I am passing the administrator username and password to the API, but it always marks access denied.
