### ISSUE TITLE
Website https suggestion and repos url

### ISSUE THREAD

**Issue by fauust** [IssabelFoundation/issabel#39]
Hi,
this is not an issue regarding the product itself but regarding your website.
"Repos" link on page https://www.issabel.org/get-issabel/ points to https://github.com/IssabelFoundation/issabel. This is an empty repository?

Your website contain non https refs so browser (firefox/chromium) gives me a warning as they consider it insecure. This may be improved, security image is key in PABX management software I think.

Regards

**Comment by asternic** [comment]
thanks for the feedback.
