### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by carlosddsilva** [IssabelFoundation/issabel#42]
I can not register the server, error when selecting country

**Comment by GregMBS** [comment]
Can you show the error text?

**Comment by carlosddsilva** [comment]
No error message appears

**Comment by GregMBS** [comment]
OK. Detailed steps to repeat error?

**Comment by carlosddsilva** [comment]
When filling in the fields to register the server, the option to select the country is blank

**Comment by GregMBS** [comment]
That would be a database error. Did the SQL databases get correctly installed?

**Comment by carlosddsilva** [comment]
An update was made from elastix to Issabel. I can not register my server

**Comment by GregMBS** [comment]
The list of countries is in the MySQL database. If Issabel cannot read the database (bad permissions, database name, username, or password) then the list will not appear.

**Comment by carlosddsilva** [comment]
As for the server this is all correct, working perfectly, I just can not register my server.

**Comment by GregMBS** [comment]
OK, then. I am out of ideas. Can anyone reproduce this?
